using System.ComponentModel.DataAnnotations;

namespace library_management_system.Server.Data.Entities
{
    /// <summary>
    /// Represents a book entity in the library management system.
    /// Defines the properties Id, Title, Author, and Description.
    /// </summary>
    public class Book
    {
        /// <summary>
        /// This property is the primary key for the Book entity.
        /// It is not set as required since it will be generated by the database.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// The title of the book.
        /// This cannot be null or empty.
        /// </summary>
        [Required(ErrorMessage = "Title is required.")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "The title must be between 1 and 100 characters.")]
        [RegularExpression(@"^[a-zA-Z0-9\s\-\.\,\;\:\!\?\'\/\""]+$", ErrorMessage = "Title can only contain letters, numbers, spaces, and basic punctuations.")]
        public required string Title { get; set; }

        /// <summary>
        /// The author of the book.
        /// This cannot be null or empty.
        /// </summary>
        [Required(ErrorMessage = "Author is required.")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "The author's name should be between 1 and 100 characters.")]
        [RegularExpression(@"^[a-zA-Z\s\-\.\,]+$", ErrorMessage = "Author name can only contain letters, spaces, hyphens, and periods")]
        public required string Author { get; set; }

        /// <summary>
        /// The description of the book.
        /// This cannot be null or empty.
        /// </summary>
        [Required(ErrorMessage = "Description is required.")]
        [StringLength(250, MinimumLength = 1, ErrorMessage = "The description should be between 1 and 250 characters.")]
        [RegularExpression(@"^[a-zA-Z0-9\s\-\.\,\:\;\!\?\'\""()]+$", ErrorMessage = "Description can only contain letters, numbers, spaces, hyphens, and basic punctuation.")]
        public required string Description { get; set; }
    }
}
